title: "Audu Abass Portfolio
description: "Audu Abass - Developer, Consultant, and Operations Expert"
author: "Audu Abass"
url: "https://yourusername.github.io/portfolio"
baseurl: "/portfolio"
paginate: 5
avatar: "/assets/images/avatar.jpg"
favicon: "/assets/images/favicon.ico"
social:
twitter: "https://x.com/Memaselfu"
linkedin: "https://linkedin.com/in/audu-abass-1121a395/"
github: "https://github.com/Xafinz"
email: "mailto:auduabass2015@gmail.com"
navigation:
- title: "Home"
url: "/"
- title: "Projects"
url: "/projects/"
- title: "About"
url: "/about/"
- title: "Contact"
url: "/contact/"
plugins:
- jekyll-seo-tag
- jekyll-feed
google_analytics: "UA-XXXXX-Y"
markdown: kramdown
